// packages/vike-lite-react/src/__internal/client/RouterApp.tsx
import { useState, useEffect, useRef, useMemo, useCallback, Component, type ReactNode, type ComponentType } from 'react'
import type { PageContextClient } from 'vike-lite'
import { matchRoute, stripBase } from 'vike-lite/__internal/shared'
import { buildNavigationPageContext, buildPageContextJsonUrl, consumeMatchingInitialContext, createLinkClickHandler, createLinkPrefetchHandler, createRoutePrefetcher, fetchPageContextJson, finalizeNavigation, loadViewModules, tryRecoverFromStaleModuleGraph, type ViewComponents } from 'vike-lite/__internal/client'
import type { VikeState } from 'vike-lite/__internal/server'

import { PageContextProvider } from '../shared/PageContextProvider'

interface RouterProps {
  routes: VikeState['routes']
  errorRoute: VikeState['errorRoute']
  initialView: ViewComponents<ComponentType<any>>
  initialContext: PageContextClient
  initialUrl: string
}

// React does not have a native functional ErrorBoundary — requires a class component
class RootErrorBoundary extends Component<{ children: ReactNode }, { error: Error | null }> {
  static getDerivedStateFromError(error: Error) { return { error } }

  override state = { error: null as Error | null }

  override render() {
    if (this.state.error) return <div>Error: {this.state.error.message}</div>
    return this.props.children
  }
}

export function RouterApp(props: RouterProps) {
  const [pageContext, setPageContextState] = useState<PageContextClient>(props.initialContext)
  const [view, setView] = useState<ViewComponents<ComponentType<any>>>(props.initialView)
  const [currentUrl, setCurrentUrl] = useState(props.initialUrl)
  const [currentPathname, setCurrentPathname] = useState(props.initialContext.urlPathname)
  const [reloadTick, setReloadTick] = useState(0)

  const shouldScrollToTop = useRef(false)
  const pendingContextOverride = useRef<Partial<PageContextClient> | null>(null)
  const reloadResolvers = useRef<Array<() => void>>([])
  const isFirstRun = useRef(true)

  const setPageContext = useCallback((updater: (prev: PageContextClient) => PageContextClient) => {
    setPageContextState(updater)
  }, [])

  const matchedRoute = useMemo(
    () => matchRoute(currentPathname, props.routes),
    [currentPathname, props.routes]
  )

  // Link interception, prefetch, popstate, programmatic events
  useEffect(() => {
    const handleLinkClick = createLinkClickHandler((url) => {
      if (!url.hash) shouldScrollToTop.current = true
      setCurrentUrl(url.href)
      setCurrentPathname(stripBase(url.pathname))
    })

    const prefetchRoute = createRoutePrefetcher()

    const handleLinkPrefetch = createLinkPrefetchHandler((url) => {
      const pathname = stripBase(url.pathname)
      const matched = matchRoute(pathname, props.routes)
      if (matched) prefetchRoute(matched.route)
    })

    const handlePopState = () => {
      setCurrentUrl(globalThis.location.href)
      setCurrentPathname(stripBase(globalThis.location.pathname))
    }

    const handleProgrammaticNavigate = (e: Event) => {
      const detail = (e as CustomEvent<{ keepScrollPosition?: boolean; pageContext?: Partial<PageContextClient> }>).detail || {}
      if (!detail.keepScrollPosition) shouldScrollToTop.current = true
      if (detail.pageContext) pendingContextOverride.current = detail.pageContext
      setCurrentUrl(globalThis.location.href)
      setCurrentPathname(stripBase(globalThis.location.pathname))
    }

    const handleProgrammaticReload = (e: Event) => {
      const resolve = (e as CustomEvent<{ resolve?: () => void }>).detail?.resolve
      if (resolve) reloadResolvers.current.push(resolve)
      setReloadTick(t => t + 1)
    }

    document.addEventListener('click', handleLinkClick)
    document.addEventListener('pointerenter', handleLinkPrefetch, { capture: true })
    document.addEventListener('focusin', handleLinkPrefetch)
    globalThis.addEventListener('popstate', handlePopState)
    globalThis.addEventListener('vike-navigate', handleProgrammaticNavigate)
    globalThis.addEventListener('vike-reload', handleProgrammaticReload)

    return () => {
      document.removeEventListener('click', handleLinkClick)
      document.removeEventListener('pointerenter', handleLinkPrefetch, { capture: true })
      document.removeEventListener('focusin', handleLinkPrefetch)
      globalThis.removeEventListener('popstate', handlePopState)
      globalThis.removeEventListener('vike-navigate', handleProgrammaticNavigate)
      globalThis.removeEventListener('vike-reload', handleProgrammaticReload)
    }
  }, [props.routes])

  // Load route
  useEffect(() => {
    const pathname = currentPathname
    const isReload = reloadTick > 0

    if (!isReload && isFirstRun.current && consumeMatchingInitialContext(pathname)) {
      isFirstRun.current = false
      return
    }
    isFirstRun.current = false

    const controller = new AbortController()
    const signal = controller.signal
    const urlFull = currentUrl
    const matched = matchedRoute

    const renderErrorPage = async (is404: boolean, message?: string) => {
      if (!props.errorRoute) return
      const errorView = await loadViewModules<ComponentType<any>>(props.errorRoute)
      if (signal.aborted) return
      setPageContext(() => ({
        ...pageContext,
        urlOriginal: urlFull,
        urlPathname: pathname,
        routeParams: {},
        is404,
        is500: !is404,
        errorMessage: message,
        isClientSide: true,
        isHydration: false
      } as PageContextClient))
      setView(errorView)
      document.title = is404 ? 'Not Found' : 'Server Error'
      finalizeNavigation(shouldScrollToTop)
    }

    const loadRoute = async () => {
      const contextOverride = pendingContextOverride.current
      pendingContextOverride.current = null

      if (!matched) return renderErrorPage(true)

      const { route, routeParams } = matched
      try {
        const urlObj = new URL(urlFull)
        const jsonUrl = buildPageContextJsonUrl(pathname, urlObj.search)

        const ctx = (route.data || route.title)
          ? await fetchPageContextJson(jsonUrl, { signal, cache: isReload ? 'no-cache' : 'default' })
          : null

        if (signal.aborted) return

        if (ctx?._redirect) {
          const urlObjRedirect = new URL(ctx._redirect, globalThis.location.origin)
          if (urlObjRedirect.origin !== globalThis.location.origin) {
            globalThis.location.assign(ctx._redirect)
            return
          }
          globalThis.history.pushState({ triggeredBy: 'vike-lite' }, '', ctx._redirect)
          shouldScrollToTop.current = true
          setCurrentUrl(urlObjRedirect.href)
          setCurrentPathname(stripBase(urlObjRedirect.pathname))
          return
        }

        if (ctx && (ctx.is404 || ctx.is500 || ctx.isError)) {
          return renderErrorPage(ctx.is404 ?? false, ctx.reason || 'Server Error')
        }

        const newView = await loadViewModules<ComponentType<any>>(route)

        if (signal.aborted) return

        setPageContext(() => buildNavigationPageContext({
          routeParams,
          urlOriginal: urlObj.href,
          urlPathname: pathname,
          search: urlObj.search,
          ...(ctx?.data !== undefined ? { data: ctx.data } : {}),
          ...(ctx?.title ? { title: ctx.title } : {}),
          ...contextOverride
        }) as PageContextClient)
        setView(newView)

        if (ctx?.title) document.title = ctx.title

        requestAnimationFrame(() => {
          if (globalThis.location.hash) return
          document.querySelector<HTMLDivElement>('#root')?.focus({ preventScroll: true })
        })

        finalizeNavigation(shouldScrollToTop)
      } catch (error) {
        if ((error as Error).name === 'AbortError') return

        const message = (error as Error).message || ''
        if (tryRecoverFromStaleModuleGraph(message, urlFull)) return

        console.error('Router Error:', error)
        renderErrorPage(false, message)
      } finally {
        if (!signal.aborted) {
          for (const resolve of reloadResolvers.current) resolve()
          reloadResolvers.current = []
        }
      }
    }

    loadRoute()
    return () => controller.abort()
  }, [currentPathname, currentUrl, matchedRoute, reloadTick])

  const { Page, Layout } = view

  const contextValue = useMemo(
    () => ({ pageContext, setPageContext }),
    [pageContext, setPageContext]
  )

  if (!Page) return null

  return (
    <RootErrorBoundary>
      <PageContextProvider value={contextValue}>
        {Layout ? <Layout><Page /></Layout> : <Page />}
      </PageContextProvider>
    </RootErrorBoundary>
  )
}

// packages/vike-lite-solid/src/__internal/RouterApp.tsx
import { type JSX, createSignal, createEffect, onCleanup, ErrorBoundary, startTransition, batch, createMemo } from 'solid-js'
import { createStore, reconcile } from 'solid-js/store'
import { isServer } from 'solid-js/web'
import type { PageContext } from 'vike-lite'
import { matchRoute } from 'vike-lite/__internal/shared'

import PageContextProvider from './PageContextProvider'

export interface ViewComponents {
  Page: any | null
  Layout: any | null
  Head: any | null
}

export interface RouterProps {
  routes: any[]
  errorRoute: any | null
  initialView: ViewComponents
  initialContext: PageContext
  initialUrl: string
}

export default function RouterApp(props: RouterProps): JSX.Element {
  const [pageContextStore, setPageContextStore] = createStore<PageContext>(props.initialContext)
  const [view, setView] = createSignal<ViewComponents>(props.initialView)

  const [currentUrl, setCurrentUrl] = createSignal(props.initialUrl)
  const [currentPathname, setCurrentPathname] = createSignal(props.initialContext.urlPathname)

  const matchedRoute = createMemo(() => matchRoute(currentPathname(), props.routes))

  if (!isServer) {
    createEffect(() => {
      const handleLinkClick = (e: MouseEvent) => {
        const target = (e.target as HTMLElement).closest('a')
        if (!target?.href || target.target === '_blank' || e.ctrlKey || e.metaKey || e.altKey || e.shiftKey) return
        const url = new URL(target.href)
        if (url.origin !== globalThis.location.origin) return
        e.preventDefault()
        globalThis.history.pushState(null, '', url.href)
        startTransition(() => {
          setCurrentUrl(url.href)
          setCurrentPathname(url.pathname)
        })
      }
      const handlePopState = () => {
        startTransition(() => {
          setCurrentUrl(globalThis.location.href)
          setCurrentPathname(globalThis.location.pathname)
        })
      }
      document.addEventListener('click', handleLinkClick)
      globalThis.addEventListener('popstate', handlePopState)
      onCleanup(() => {
        document.removeEventListener('click', handleLinkClick)
        globalThis.removeEventListener('popstate', handlePopState)
      })
    })

    createEffect(() => {
      const pathname = currentPathname()

      // Salta il fetch se i dati sono già quelli del server
      if (globalThis.__PAGE_CONTEXT__ && globalThis.__PAGE_CONTEXT__.urlPathname === pathname) {
        globalThis.__PAGE_CONTEXT__.urlPathname = undefined
        return
      }

      const controller = new AbortController()
      const urlFull = currentUrl()
      const matched = matchedRoute()

      const loadRoute = async (signal: AbortSignal) => {
        if (!matched) return

        const { route, routeParams } = matched
        try {
          const urlObj = new URL(urlFull)
          const jsonUrl = `${pathname === '/' ? '/index' : pathname}.pageContext.json${urlObj.search}`

          const [PageMod, LayoutMod, HeadMod, ctx] = await Promise.all([
            route.Page(),
            route.Layout?.() ?? null,
            route.Head?.() ?? null,
            // eslint-disable-next-line unicorn/prefer-await
            route.hasData || route.hasTitle ? fetch(jsonUrl, { signal }).then(r => r.json() as Promise<PageContext>) : null
          ])

          if (signal.aborted) return

          batch(() => {
            setPageContextStore(reconcile({
              routeParams,
              urlOriginal: urlObj.href,
              urlPathname: pathname,
              ...(ctx?.data && { data: ctx.data }),
              ...(ctx?.title && { title: ctx.title })
            }))
            setView({
              Page: PageMod.Page ?? PageMod.default,
              Layout: LayoutMod?.Layout ?? LayoutMod?.default ?? null,
              Head: HeadMod?.Head ?? HeadMod?.default ?? null
            })
          })
          if (ctx?.title) document.title = ctx.title

        } catch { }
      }

      loadRoute(controller.signal)
      onCleanup(() => controller.abort())
    })
  }

  return (
    <ErrorBoundary fallback={(err: Error) => <div>Error: {err.message}</div>}>
      <PageContextProvider pageContext={pageContextStore} setPageContext={setPageContextStore}>
        {(() => {
          const { Page, Layout } = view()
          return <>{Layout ? <Layout><Page /></Layout> : <Page />}</>
        })()}
      </PageContextProvider>
    </ErrorBoundary>
  )
}
