// packages/vike-lite-react/src/__internal/shared/PageContextProvider.tsx
import type { ReactNode } from 'react'

import { PageContextReactContext, type PageContextValue } from '../../shared/globalContext'

export function PageContextProvider({
  value,
  children
}: {
  value: PageContextValue
  children: ReactNode
}) {
  return (
    <PageContextReactContext.Provider value={value}>
      {children}
    </PageContextReactContext.Provider>
  )
}

// packages/vike-lite-solid/src/__internal/shared/PageContextProvider.tsx
import type { JSX } from 'solid-js'
import type { SetStoreFunction, Store } from 'solid-js/store'
import type { PageContext } from 'vike-lite'

import { globalContext } from '../../shared/globalContext'

export function PageContextProvider(props: {
  children: JSX.Element
  pageContext: Store<PageContext>
  setPageContext: SetStoreFunction<PageContext>
}) {
  const Provider = globalContext.solidContext.Provider

  return (
    <Provider value={{
      get state() { return props.pageContext },
      get setState() { return props.setPageContext }
    }}>
      {props.children}
    </Provider>
  )
}
