// packages/vike-lite-solid/src/hooks/globalContext.tsx
import { createContext, type Context } from 'solid-js'
import type { SetStoreFunction, Store } from 'solid-js/store'
import type { PageContext } from 'vike-lite'

export interface InternalContextValue<Data = unknown> {
  state: Store<PageContext<Data>>
  setState: SetStoreFunction<PageContext<Data>>
}

const KEY = Symbol.for('vike-lite-solid:context')

type GlobalContext = { solidContext: Context<InternalContextValue<unknown> | undefined> }

export const globalContext: GlobalContext =
  (globalThis as { [KEY]?: GlobalContext | undefined })[KEY] ??= { solidContext: createContext<InternalContextValue<unknown>>() }

// packages/vike-lite-react/src/hooks/globalContext.tsx
import { createContext } from 'react'
import type { PageContext } from 'vike-lite'

export interface PageContextValue {
  pageContext: PageContext
  setPageContext: (updater: (prev: PageContext) => PageContext) => void
}

const KEY = '__vike_lite_react_context__'
const g = globalThis as any

if (!Object.hasOwn(g, KEY)) {
  g[KEY] = createContext<PageContextValue | null>(null)
}

export const PageContextReactContext = g[KEY] as React.Context<PageContextValue | null>
