// packages/vike-lite-react/src/shared/globalContext.tsx
import { createContext, type Context } from 'react'
import type { PageContextClient } from 'vike-lite'

export interface PageContextValue {
  pageContext: PageContextClient
  setPageContext: (updater: (prev: PageContextClient) => PageContextClient) => void
}

type PageContextReactContext = Context<PageContextValue | null>

const KEY = Symbol.for('vike-lite-react:context')

export const PageContextReactContext: PageContextReactContext =
  (globalThis as { [KEY]?: PageContextReactContext | undefined })[KEY] ??= createContext<PageContextValue | null>(null)

// packages/vike-lite-solid/src/hooks/globalContext.tsx
import { createContext, type Context } from 'solid-js'
import type { SetStoreFunction, Store } from 'solid-js/store'
import type { PageContext } from 'vike-lite'

export interface InternalContextValue<Data = unknown> {
  state: Store<PageContext<Data>>
  setState: SetStoreFunction<PageContext<Data>>
}

const KEY = Symbol.for('vike-lite-solid:context')

type GlobalContext = { solidContext: Context<InternalContextValue<unknown> | undefined> }

export const globalContext: GlobalContext =
  (globalThis as { [KEY]?: GlobalContext | undefined })[KEY] ??= { solidContext: createContext<InternalContextValue<unknown>>() }
