// packages/vike-lite-react/src/hooks/useData.tsx
import { useContext, useCallback } from 'react'

import { PageContextReactContext } from '../shared/globalContext'

export function useData<Data = unknown>(): [Data, (updater: Data | ((prev: Data) => Data)) => void] {
  const ctx = useContext(PageContextReactContext)
  if (!ctx) throw new Error('useData() must be called inside a page rendered by vike-lite-react')

  const data = ctx.pageContext.data as Data

  const setData = useCallback((updater: Data | ((prev: Data) => Data)) => {
    ctx.setPageContext(prev => ({
      ...prev,
      data: typeof updater === 'function' ? (updater as (prev: Data) => Data)(prev.data as Data) : updater
    }))
  }, [ctx])

  return [data, setData]
}

// packages/vike-lite-solid/src/hooks/useData.tsx
import { useContext } from 'solid-js'
import type { SetStoreFunction } from 'solid-js/store'
import type { PageContext } from 'vike-lite'

import { globalContext } from '../shared/globalContext'

/**
 * Hook dedicated to `data` for convenience (returns getter and setter as an array).
 * @link https://github.com/vikejs/vike-solid/blob/main/packages/vike-solid/hooks/useData.tsx
 */
export function useData<Data extends PageContext['data']>(): [Data, SetStoreFunction<Data>] {
  const context = useContext(globalContext.solidContext)
  if (!context) throw new Error('useData() must be called inside a page rendered by vike-lite-solid')

  const setData: SetStoreFunction<Data> = (...args: unknown[]) => {
    // @ts-expect-error - pass args directly to 'data'
    context.setState('data', ...args)
  }

  return [context.state.data as Data, setData]
}
